[tox]
envlist = py310, py311
isolated_build = True

[testenv]
deps =
    urllib3>=2.7.0
    pytest
    pytest-cov
    atheris<3.0.0
commands =
    pytest --cov=./ --cov-report=term-missing --cov-fail-under=100
passenv = *

[gh-actions]
python =
    3.10.20: py310
    3.11.13: py311

[tox.sdist]
exclude =
    .git
    .github
    .venv
    .pytest_cache
    .coverage
    __pycache__
    uv.lock
